### ISSUE TITLE
Buttons and Switches aren't linked to the device

### ISSUE THREAD

**Issue by cvroque** [Amateur-God/home-assistant-technitiumdns#31] opened 2024-08-21 17:52 UTC
# Problem/Motivation

> Buttons aren't showing up on the device page!

## Expected behavior

> All entities available on the device page

## Actual behavior

> The integration adds 1 device and 27 entities, but only 21 (the sensors) are linked to the device it creates. I believe the buttons also are lacking unique ids.

## Steps to reproduce

> I just configured the integration and checked the devices:
![image](https://github.com/user-attachments/assets/01640449-4c34-4239-9d02-3c2344bee7cc)

## Proposed changes

> Thanks for the great integration! It doesn't stop the buttons from working, but make these harder to find.

**Comment by cvroque** [comment] 2024-08-21 18:36
> This is odd, can you see what entities you have? I'm unable to recreate this issue

The first 6 on this screenshot are the ones not showing:
![image](https://github.com/user-attachments/assets/c19abf6f-7a55-4806-924b-80d6288e53a0)
And here's the device page:
![image](https://github.com/user-attachments/assets/81a06d29-39e2-4b5c-a5f3-a39ad1356dfb)

Thanks again!

**Comment by Amateur-God** [comment] 2024-08-21 18:43
can you try removing your DNS server and updating to the latest version of the integration and then reconfiguring your DNS server

**Comment by cvroque** [comment] 2024-08-21 19:24
Despite the screenshot showing 2,2.1, I'm actually on the latest:
![image](https://github.com/user-attachments/assets/f9f6f081-ec6b-4bfc-bdb5-8869f1228450)
I tried removing the integration, restarting and adding again with the same results.
Here's the other version details:
![image](https://github.com/user-attachments/assets/4941ecc8-408c-4737-af94-057571c4a333)

I enabled debug logging for technitiumdns and attached the results.
[DEBUG.LOG](https://github.com/user-attachments/files/16697749/DEBUG.LOG)
I believe this may be related:
![image](https://github.com/user-attachments/assets/d64d0e16-65cd-431c-9616-83d0177b1c55)

**Comment by Amateur-God** [comment] 2024-08-21 19:42
Ive just updated my HASOS and replicated the issue, seems to be something caused by the new update, ive pushed a beta release to attempt to fix this, feel free to load that, i usually move them from beta to live after ive tested it for a week or 2 

https://github.com/Amateur-God/home-assistant-technitiumdns/releases/tag/v2.2.3-beta.1

**Comment by cvroque** [comment] 2024-08-21 20:04
> Ive just updated my HASOS and replicated the issue, seems to be something caused by the new update, ive pushed a beta release to attempt to fix this, feel free to load that, i usually move them from beta to live after ive tested it for a week or 2
> 
> https://github.com/Amateur-God/home-assistant-technitiumdns/releases/tag/v2.2.3-beta.1

Thanks, I just tested it and everything is in place, except the switch to enable/disable adblocking which is missing entirely.

**Comment by Amateur-God** [comment] 2024-08-21 20:11
> > Ive just updated my HASOS and replicated the issue, seems to be something caused by the new update, ive pushed a beta release to attempt to fix this, feel free to load that, i usually move them from beta to live after ive tested it for a week or 2
> > https://github.com/Amateur-God/home-assistant-technitiumdns/releases/tag/v2.2.3-beta.1
> 
> Thanks, I just tested it and everything is in place, except the switch to enable/disable adblocking which is missing entirely.
> 
> ![image](https://private-user-images.githubusercontent.com/65680394/360081625-ea047c22-1bee-427d-bb7e-35f6f4d24c10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNzEwMDYsIm5iZiI6MTcyNDI3MDcwNiwicGF0aCI6Ii82NTY4MDM5NC8zNjAwODE2MjUtZWEwNDdjMjItMWJlZS00MjdkLWJiN2UtMzVmNmY0ZDI0YzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDIwMDUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZjcyYzI3ZGI3ZDQ0NDY3NTk4MDI5ZmMzY2YxZmUwODAxNmFjOGNhMjg3ODU4MDQxMGE5NWQ0ZTk0OTU4Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-4ffSesgTJUHJhUmvLCCRS5kfPgo6vQ_Rw2z-pZgwCA)

Yeah ive just realised that i mistakingly put duration as a UniqueID attribute for switches like i did with buttons completely forgetting they dont have a duration attribute


should be fixed in 

https://github.com/Amateur-God/home-assistant-technitiumdns/releases/tag/v2.2.3-Beta.2|

sorry about that ive been coding all day so a little burnt out

**Comment by cvroque** [comment] 2024-08-21 21:36
It's perfect now, there's nothing to apologize for, thanks for the great integration and fast replies!

**Comment by Amateur-God** [comment] 2024-08-21 21:39
Just reopening this while the fix is in beta for anyone else who has the issue 
and as a reminder to me to move beta to live after testing thoroughly

**Closed** 2024-08-27 10:48 UTC
Labels: In Beta

**Comment by Amateur-God** [comment] 2024-08-27 13:32
you may need to re-add the switches as i fixed a typo in entity names
