### ISSUE TITLE
Missing Sensors? Fresh Install

### ISSUE THREAD

**Issue by Krystm** [Amateur-God/home-assistant-technitiumdns#35] opened 2024-10-14 12:39 UTC
# Problem/Motivation

Did the HACS Install (2.2.3), Linked as Admin-Level account. I can pause / stop blocking. However No sensors were found / created for the stats. Currently on HA 10.0.2. 

## Expected behavior

That sensors would auto show on the device. Have Removed and Re-Added Multiple Times.

## Actual behavior

I get the buttons to enable / disable (and they tested working), but no list of sensor items. 

## Steps to reproduce

Clean Install is all I did. I did try adding the config to the yaml as well but instructions are somewhat unclear if all you need to do for the HACS install is just add the custom integration and install (which figured since also a warning saying it wouldn't use any config from the yaml) So not sure what else to try.  I did try to do due diligence to see if anyone else had reported any issues etc but couldn't find any hence this issue. 

<img width="698" alt="Screenshot 2024-10-14 at 7 37 59 AM" src="https://github.com/user-attachments/assets/8a7fa6c4-2716-40ef-9866-e86dba5f0710">

**Comment by Amateur-God** [comment] 2024-10-15 13:09
I have tried to recreate this on a fresh install on a new VM. However, so far, I haven't had any luck. Do you have any other custom integrations or plugins that could be causing a conflict anywhere?

**Comment by Amateur-God** [comment] 2024-10-15 13:22
> I do have quite an extensive setup. Is there anything I should look for specifically? I would figure should just be data pulling from the DNS Server but I can certainly look. Like I stated the Buttons to disable / Enable and temp disable timer buttons all work. So the connection seems to be there. I dont see any logs about failures, but not 100 sure where to look for specific logs. If ya can point me in the right direction maybe can find it.

the only thing i can think of is if for some reason another integration you have has the same sensor names or entry_ID as these however that would only happen if for some reason another integration uses technitium as the domain name of the integration.

the only other thing i could think of would be something in the settings for your DNS

**Comment by Krystm** [comment] 2024-10-15 13:26
Yeah Im checking that right now, I just VLANed out my networks and separated my IoT from everything else and this was the reason to run Technitium. However, the HA device does have access to the device, but I am checking the user account / api token if maybe somehow doesnt have permissions. What is the suggested access for this? I was thinking admin since you are able to enable/disable blocking, but wasn't sure on that. I am usually about least privilege, but understand the need with that.

**Comment by Amateur-God** [comment] 2024-10-15 13:48
so on mine i created a new user called hasse and gave it DNS Administrator role, That the highest level of access required allows it to do DNS stuff like enable/disable ad blocking without having full admin access to settings 

![image](https://github.com/user-attachments/assets/fc720a0c-95ba-487d-87f0-6e9a12ad8304)


The server name in the config is just what you want it to be called in HA for example i have mine as DNS1 and DNS2 

did you put the IP in for the dns server or did you use a local domain like dns.local?

for the dns server domain on your screenshots, technitium isnt a FQDN an fqdn would be something like dns.local but that shouldnt affect the integration as the integration doesnt call that from the API 

what do your logging settings look like in Technitium?

**Comment by Amateur-God** [comment] 2024-10-15 13:53
also can you enable debug logging and try to readd the integration and see if you get any errors?

**Comment by Krystm** [comment] 2024-10-15 13:56
<img width="1145" alt="Screenshot 2024-10-15 at 8 51 12 AM" src="https://github.com/user-attachments/assets/43bf4495-7f05-4a88-b117-8b4d57c63c5a">

Standard default logging, I am using the IP Address and Port of the Server that is exposed on that vlan and do have the webservice listening on that IP. (I'd suspect issues with even the buttons if that was incorrect). So the only thing that should matter on the config from the Technitium Side is the API Key, IP (with port?) and then the User it belongs to. I have an exporter account I will give DNS Admin to. Ill check debug gotta turn that on assuming youre looking for HA logs?

**Comment by Amateur-God** [comment] 2024-10-15 14:00
>  Ill check debug gotta turn that on assuming youre looking for HA logs?

yep sorry i meant HA logs, also do you have anything API related in the Technitium logs?

**Comment by Krystm** [comment] 2024-10-15 14:02
So this is odd. I can access the DNS Server from HA's Terminal however I am seeing timeouts on the API reading sensors. But the main 6 buttons are there.
<img width="1186" alt="Screenshot 2024-10-15 at 9 00 07 AM" src="https://github.com/user-attachments/assets/e66faf33-1d41-48d3-bf12-06f18f1f4bcd">

Checking the Tech logs now

**Comment by Amateur-God** [comment] 2024-10-15 14:06
ill increase the timout and handle the top error too, im about to release a new beta ill add these to it to see if it fixes your error

**Comment by Krystm** [comment] 2024-10-15 14:12
also can see the session in tech. Im gonna turn on debug, delete/re-add the add on. 
<img width="751" alt="Screenshot 2024-10-15 at 9 11 38 AM" src="https://github.com/user-attachments/assets/5af0137c-9943-4c37-b452-d3117df9a59e">

**Comment by Amateur-God** [comment] 2024-10-15 14:15
> Ok Sounds good! Let me know if I can be of any help. I generated a new API Token since I had changed the user access to DNS Admin and that token connected but buttons dont work anymore. So maybe needs a higher level of administration, but I added my exporter to the admin group like your screenshot.

i may have changed my perms and forgot about it but these are the perms required 

![image](https://github.com/user-attachments/assets/e632d598-f1b5-43a5-9385-3daf62c47d09)

**Comment by Amateur-God** [comment] 2024-10-15 14:20
this hasnt been tested yet and i cant guarantee i havent completely broken stuff but if you want to try it out before ive had chance to test it you are welcome to 

https://github.com/Amateur-God/home-assistant-technitiumdns/releases/tag/v2.3.0-Beta.1

**Comment by Krystm** [comment] 2024-10-15 14:20
Ok heres the debug am I using the wrong URL by chance?
<img width="1075" alt="Screenshot 2024-10-15 at 9 19 06 AM" src="https://github.com/user-attachments/assets/226c33ce-2900-4b2f-803d-fc124e7700aa">

**Comment by Krystm** [comment] 2024-10-15 14:23
Also How Do I deploy the Beta From HACS? It sees it in the top right but I cant remeber where I saw where you can choose the version you install. Do I have to re add the Repo?

**Comment by Amateur-God** [comment] 2024-10-15 14:24
> Also How Do I deploy the Beta From HACS? It sees it in the top right but I cant remeber where I saw where you can choose the version you install. Do I have to re add the Repo?

you just click the 3 dots and there should be a choose version option then tick enable beta or enable pre releases or something then just choose the beta in the dropdown

**Comment by Krystm** [comment] 2024-10-15 14:26
I removed the install from HACS and then Re-Installed. Ill let ya know give me a few. Does the URL look right? just http://IP:Port right?

**Comment by Krystm** [comment] 2024-10-15 14:36
Seems like its not connecting. I know it does have access, I can ssh from the HA terminal and have seen the Session in tech. Ill try deleting the session maybe thats blocking it. 

<img width="1171" alt="Screenshot 2024-10-15 at 9 34 45 AM" src="https://github.com/user-attachments/assets/ee20911d-5a71-49b6-a5ea-aef7ac8e224a">

**Comment by Amateur-God** [comment] 2024-10-15 14:41
> I removed the install from HACS and then Re-Installed. Ill let ya know give me a few. Does the URL look right? just http://IP:Port right?
> 

Yeah that should be correct as long as it's the correct IP and port

**Comment by Amateur-God** [comment] 2024-10-15 14:41
I have mine on separate VLANs too so it should work

**Comment by Krystm** [comment] 2024-10-15 14:50
Nothing in FW but did find this in the Tech logs. 

[2024-10-15 14:33:38 UTC] [172.31.246.3:45110] Check for update was done {updateAvailable: False;}
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at TechnitiumLibrary.Net.Http.Client.HttpClientNetworkHandler.InternalSendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Http\Client\HttpClientNetworkHandler.cs:line 99
   at TechnitiumLibrary.Net.Http.Client.HttpClientNetworkHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Http\Client\HttpClientNetworkHandler.cs:line 242
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DnsServerCore.WebServiceApi.GetCheckForUpdateJsonData() in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebServiceApi.cs:line 80
   at DnsServerCore.WebServiceApi.CheckForUpdateAsync(HttpContext context) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebServiceApi.cs:line 104

**Comment by Krystm** [comment] 2024-10-15 14:58
Ok, Not sure where else to go but I did make manual API requests in the browser and it works there so I know the keys are good at least. 
<img width="338" alt="Screenshot 2024-10-15 at 9 58 19 AM" src="https://github.com/user-attachments/assets/b6c17a37-9fa9-4343-9d6b-434b2399df1c">

**Comment by Amateur-God** [comment] 2024-10-15 15:31
tbh we have looked at everything i could think of i noticed my technitium server needed updating so i just updated to the latest version to make sure no api stuff had changed and mine is pulling all of the sensors and everything still.

without being able to recreate this there isnt much i can do to fix it unfortunately, everything is pointing to an issue with your home assistant integration not being able to connect to the technitium server but then you are able to connect to it via terminal which tbh puts me at a loss tbh. i dont really think there is much i can do at the moment.

do you have anything in your technitium about connection refused or anything like that?

**Comment by Amateur-God** [comment] 2024-10-15 15:35
also if you go to your home assistant logs for core and click load full logs is there anything in there related to the integration

**Comment by Krystm** [comment] 2024-10-15 15:35
I looked by IP and didn't see anything there. I stay bleeding edge though so maybe a random update will fix it lol. I have like 1 or 2 other things I'm gonna try to see if it takes. Cause It used to connect and I even had the buttons AND they worked. Just didnt have the logs. Now it doesnt seem to connect at all.  Ok Ill check full logs one sec.

**Comment by Amateur-God** [comment] 2024-10-15 15:44
this is strange i cant see any reason why it wouldnt connect, you are doing http://ip:port right for the integration setup

**Comment by Krystm** [comment] 2024-10-15 15:45
correct http://172.x.x.x:5380

**Comment by Amateur-God** [comment] 2024-10-15 15:48
in home assistant you go into dev tools, go to states and where it says filter entities click there and put in dns or whatever name you gave the integration when you added it do they show up in there?

**Comment by Krystm** [comment] 2024-10-15 15:56
Nada - I even tried GPT rewriting the api.py and sensor.py as it had some suggestions but no changes. It really does seem like its just being blocked from sending API commands, but so weird they work from the terminal driectly
<img width="1341" alt="Screenshot 2024-10-15 at 10 54 01 AM" src="https://github.com/user-attachments/assets/a9a6b521-2628-4723-b2ed-ed4ef1a73194">
<img width="636" alt="Screenshot 2024-10-15 at 10 55 51 AM" src="https://github.com/user-attachments/assets/9dbabeaa-a644-454f-a3cc-e169594fe20d">

**Comment by Amateur-God** [comment] 2024-10-15 16:03
fair warning GPT isnt great at python or at APIs even if you provide it with documents, i provided it with the latest api docs for Technitium because i didnt want to read through a wall of text and asked it to tell me if there was any new API endpoints i can use and it just straight up made some up and i trusted it which lead me to creating sensors and api calls for them to find out they didnt actually exist.

ive also found when ive tried to use it before to help me debug stuff in discord.py when i first started coding it would just straight up make stuff up that dont actually exist and give me suggestions to improve my code which would just break it

unfortunately, i cant recreate this issue, i thought i had a moment a go but then it was just the browser being slow to update and sadly without being able to recreate it and this being the only issue of this type it seems like its an issue somewhere in your internal network and not a bug with the integration and as such im going to have to close the issue.

the only thing i can suggest is checking your interVLAN firewall rules and making sure there is nothing there that could be blocking anything

**Closed by Amateur-God** 2024-10-15 16:03 UTC
Labels: help wanted

**Comment by Krystm** [comment] 2024-10-15 16:07
I just checked my PAFW and its not crosssing any vlans so intervlanning isn't the issue there. But Im thinking about making a virtual interface in another vlan and shooting it over to see if maybe that could do it. 

so funny thing... that screen shot says 2.2.3 should be the beta. I removed the Repo in HACS and re added it, it asked what version which I chose the latest one in beta. So thats also weird.

As far as GPT, absolutely understand, I had a lot of the same experiences with it, just kinda was going all or nothing at this point lol.

**Comment by Amateur-God** [comment] 2024-10-15 16:16
> so funny thing... that screen shot says 2.2.3 should be the beta. I removed the Repo in HACS and re added it, it asked what version which I chose the latest one in beta. So thats also weird. But not if you dont change that in the betas. But I am updating from .1 to .3 to see if it helps.

it should say 2.3.0 as thats what the manifest says, did you restart home assistant after redownloading the beta?

it should say it here in HACS

![image](https://github.com/user-attachments/assets/b8276584-efcb-4576-ac93-740698643cc8)
where the box thing is thats version downloaded 

and here in integration it should say 2.3.0

![image](https://github.com/user-attachments/assets/af272dd8-e52c-4354-9c44-026ccf544cd5)

**Comment by Krystm** [comment] 2024-10-15 16:18
Yes it showing 2.3.0 there now. and I was doing restarts of HA after each install / removal (not full reboot) but a full HA service restart.

**Comment by Amateur-God** [comment] 2024-10-15 16:22
well unfortunately im out of ideas, its definitely not an issue with the integration as i have tried multiple times to reproduce it and couldn't and this is the only issue like this ive had opened. 

i would look through any settings for Firewalls or AppArmor on the hosts of either and see if there is anything on either that could be preventing the connection.

personally i recommend using HAOS in a VM for full HA features
